replicaCount: 1

ingress:
  hosts:
    - host: amang-api.json-server.win
      paths:
        - path: /
          pathType: Prefix

env:
  NODE_ENV: production
  ACCESS_TOKEN_SECRET: aasfeawfawjfiawefiawenifn23r4239rj23
  REFRESH_TOKEN_SECRET: aasfeawfawjfiawefiawenifn23r4239rj23
  DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres?schema=public # TODO: Update with actual database URL

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
