replicaCount: 1

image:
  repository: ghcr.io/skku-amang/amang-api
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: amang-api.json-server.win
      paths:
        - path: /
          pathType: Prefix

env:
  NODE_ENV: production
  ACCESS_TOKEN_SECRET: aasfeawfawjfiawefiawenifn23r4239rj23
  REFRESH_TOKEN_SECRET: aasfeawfawjfiawefiawenifn23r4239rj23
  DATABASE_URL: "postgresql://amang:amang123@amang-db-postgresql.amang-db.svc.cluster.local:5432/amang?schema=public"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
