FROM node:22-alpine AS base
RUN npm install -g pnpm turbo@^2

FROM base AS installer
RUN apk update
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY . .

RUN pnpm install --frozen-lockfile

RUN turbo db:generate

ENV NODE_ENV=development
ENV HOSTNAME="0.0.0.0"
ENV PORT=3000

EXPOSE 3000

CMD ["pnpm", "run", "dev", "--filter=web"]