apiVersion: v1
kind: Secret
metadata:
  name: amang-db-credentials
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "cloudbeaver"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "cloudbeaver"
type: Opaque
stringData:
  POSTGRES_DB: amang_db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
