---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: amang-redis-production
spec:
  encryptedData:
    REDIS_PASSWORD: AgAhgs7c8c+gKNwlGDXVP9OLbvttIW+IK7bVm5q+llFrwZbQLDOXsgg/njS9MUiLCsOwnPAOZ/nX/qNQLpYdC8J+7NPMrQHUkC4WLRZVWu/dp41YTGt2cTdC10jSzuUXBYwRl59r0ayVF2X7QbDex3JDjWLXTbNOKe+55i29S4jqEnk2shQB0Tdxg7uiSDLdpHF6uL1uuojRV57S4aVT2WSdNevYaczBPcHn1k7MPlvyL2FNPIPwOeo5SYm6e973ExAyZtngb3Un+QnL1UNHKqNqFUDzMmt9s6RA+iT6zAE+ZB/vjdDxIKOrB1bdJWItAmEsrvaJ06T3xaZ0YV9RTGKowhiJyqCONOzx/e4Y39FiAlS+jLHut8tyh7xwsNrPKvLoxs0HrMpLHp5/LSRy4vchX7yzWzp841BvCfRUz2Kwbxh6IT46MJi2OwedguvmgAh3TUQpwCV9qTgZgP4naAh2P5z7uV1l4LDBTDfPoaIj09hWfvHOA0UWYsT5erDk0fddDpda504VLQ83OjZWc3SJJQ2L00lLlaKvR9NdNC92eYvws7C7oFiS4PD9ApMT4vY/G2/6ETLWdl2T9BSDjtersnzuo2WOLe3aojan1Is7iwYa5pAve52eqwG2PODEApJy3R4sRWRan3XbslV3hCja2GeAIuU9m3icJqufQLWuCiLQknG8rCm38glL+v7TZsbryWtvmEtnF2Tn8rtS6Qaj7jE2vCQzDBNrWx+lDMoDZA==
  template:
    metadata:
      name: redis-credentials
      namespace: amang-redis-production
