apiVersion: v1
kind: ConfigMap
metadata:
  name: amang-web-config
  namespace: amang-web
  labels:
    app: amang-web
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}