apiVersion: v1
kind: Service
metadata:
  name: amang-web-service
  labels:
    app: amang-web
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: amang-web
