apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: api

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - ingress.yaml
  - migrate-job.yaml
  - service.yaml
