replicaCount: 1

ingress:
  hosts:
    - host: amang-staging.json-server.win
      paths:
        - path: /
          pathType: Prefix

env:
  NODE_ENV: development
  NEXT_PUBLIC_API_URL: "https://amang-staging-api.json-server.win"

resources:
  limits:
    cpu: 300m
    memory: 256Mi
