---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: amang-redis-staging
spec:
  encryptedData:
    REDIS_PASSWORD: AgCDYRwwK3iMTn7QThvHp6PgdPP+7x7Eyyl2ecSbwV1WHMNia5chA6g8CxlqDgjXsgbLo3IYcMHTIFaqBZfHh5kIbK0wXvtwK0toS141GDcrvUWpKSWANLb5dAR0g0n6jZJF2LRICW757RBDSR1BuOWLA61ldsvbrxszVVYGazvremVpBYTWQBspvyO7flZdmAQpHEO06EgA7Zd0CRgJlsDWJuwzaid+1qpl40xn8s0TNDBvHB2ENFLuKasfdTY2hagBZuA+gL1HvrtKZ3TIjbeGlpupKzyktwyYWDUjCxAlrYBMOCQRZ0b1ixbvWk0hrVWV28QL+s+F+A8wju/X1rUXFhRFEPGteKgEv9cUpEuFjw+UHJIqHX/0le4nibo61XJAC4yBE2Pz2WOqK/8JDkuzWdNXjXAp8fIg3GJZrTBsKOdQRFIpJOSewV5S0yPefH4dxWAR9SHdN+0W0UpBhSrhd26CyT+dmmg8HplnSfgngA0ukGLIiktBO+2Z11qzyzmyu+cJhjLublsoeinnTwPOP1p29FxxjCpat7yZfP3k5jeIYA1sCTWW5WD+j0Cri2MHeEVhzt3/6D3ja4Hxp9ZdYOS5qe0yE9ZiGDt8kNyWIx/fiH1O6z2fIIzgizuh/ZNfXRqHjHckLuHf5VR88kSVXvjpYkcreqw9X4kl4GNrLkjII7nqllgl78fmvWrd6e9t55T8R12GMMFoqN1AFoe6kIOg++Jf63cJnalSDOU8VQ==
  template:
    metadata:
      name: redis-credentials
      namespace: amang-redis-staging
