replicaCount: 1

image:
  repository: ghcr.io/skku-amang/amang-web
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: amang.json-server.win
      paths:
        - path: /
          pathType: Prefix

env:
  NEXT_PUBLIC_API_URL: "https://amang-api.json-server.win"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
