apiVersion: batch/v1
kind: Job
metadata:
  generateName: api-migrate-
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: migration-runner
          image: ghcr.io/skku-amang/amang-api:latest
          imagePullPolicy: IfNotPresent
          command: ["pnpm", "--filter", "@repo/database", "db:deploy"]
          envFrom:
            - configMapRef:
                name: api-config
      restartPolicy: Never
  backoffLimit: 2
