---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-secrets
  namespace: amang-api-production
spec:
  encryptedData:
    ACCESS_TOKEN_SECRET: AgB+HfVcelopm0QSL6EHlMCW7ZAoeEO8iL7qx8o4LNeapU/I/o+vLb2Ve1C6IBXhIwFdJVGF+uCIZ87HCx51o9YyhLeRDp9FpiuiD0na31pSpK0iIzG1Ez/+rgmoLwKr4NNDCPPVf7W4RhWRDwv1GmH1Yrxrey86R+8BiwXPl/OakIuoFDOaEZWDx4K4WZ5bZKxOljLDb26CLv/rrqhmZCR+0yFdYZ/RaUvGtIbmij+s4kW/ANDDsnO0+A31cNZ5gcD6XAJSnbfnYuzhFo+qSCFIwwDzj72wj43a9xLll3GCttZhVC7J03hzpMwC/7yDDPWJjlPjs2DPJgrmDTjm84WlIlisQDYPXW6i3SNRunl0yqMyAti37isCh0x4QUE22jIxJNi7rqTQLI/plNppOG409DN17mxlBOhwL0wKTqpYezqPzLlI+/GJRwO5xfU86jJgG3rQUPfweFpzfKHxii3VeviV7K3WwkhXiaOe1Y+GzD5V3Y5vUiZdxyBdu57JAr92FMihPVCbqKuiaRWYmtSOVtotUxiJ9Kc84nCs4pg7xASI8TQilQmjme+NYqXLACf0tx1wzzlled34MdnspZ/kz5Y9l5G4S1/cNBAYmbc83FRcCrxE7cDpQZgDiHt0T7tPnecQBaL1wPkaYcsfry4rpEMyIyKfv3wfot1KH7CRLCrTPSiYKx2GWCysM1n26ETDp8tCJNUEv5niJK58AyO7ucR2+kBhrimKD2GpI0VDUsNhTQSAVFbA76l5HwY5Z4XR6bx/N9JD5H6+WSIRg4YO
    REFRESH_TOKEN_SECRET: AgC+7j4zpC2nKWQ2+RXKpe6tgtEwgqVVugcV+iqYKpFxl56f51DBI1taS4GHN8TZsSwXm42c7jO9s6fQpzoG3KMP9fgICB0DBxUbCmV6a4pQbo7i+9tjMZohQadg+LSzXnx2Zy5Dm1QLCtmjxceWITDWsOgNaqvN8gOiJ4oLqA9OrgOlmDMpxHEGZZU1vB7bBefDlgXYASYK/1MS4PmUyOEOfTe1MOe7/o7doERDTbVCNhGNrpYPtrmcsr6PO0Liaxv7hcNoMMV7Qc9o8H0RaV8TmKZTy5x8ozUV9BQRHeIXxNoS/MQVeVyKTrXIGFQ1EZw7iUK1dKKCxDbEQLoGx612knSaV5zLkqEx3DjebdRbDA2D7fZYeOdInBujYGIJA525RbXXSdn2f35FHEjXdO+Qng0pzfcv/Yq0b6GCz48tGzze0BnRjeP0x2YqXs3R3AbgkVc9bbjtJvwX5nAiJQHxtY9pHNbsvNKRsIHbL3L7bLC3ERVRPLRuOiu1Wu/0ogiVyet2M/lKYpyCD5tvF3rA3mTkOnhnJhfz6qpK45HiA7yQ/FsoHcpa0nCg555fgWBQOzdQruHAdmPtSHZ630bJieRI3DXRoGvBYV5ap0JR3pZYi3mtVYs+nyx5ezzW5MPtbFXc9q2mL0CSa5uc1g62tP2mrxayEkudG7yV/HumIJTZhyaMo97DartRTmvv653bw7Gf959lhn4KGgRmzDgkz+AR+71KpPP8Oas9czHUoPfGsRPHcwaTQYBp6cmWstdVbawe3oRCd8csIxf7Qsfv
  template:
    metadata:
      name: api-secrets
      namespace: amang-api-production
    type: Opaque
