apiVersion: v1
kind: ConfigMap
metadata:
  name: amang-api-config
  namespace: amang-api
  labels:
    app: amang-api
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}