apiVersion: v1
kind: Service
metadata:
  name: amang-api-service
  labels:
    app: amang-api
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: amang-api
