name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false # 하나 실패해도 다른 것들 계속 실행
      matrix:
        app:
          - name: web
            dockerfile: apps/web/Dockerfile.dev
          - name: api
            dockerfile: apps/api/Dockerfile
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ matrix.app.name }} image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.app.dockerfile }}
          push: true
          tags: |
            ghcr.io/skku-amang/amang-${{ matrix.app.name }}:${{ github.sha }}
            ghcr.io/skku-amang/amang-${{ matrix.app.name }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
